# Generated by Django 5.0.6 on 2024-06-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_post',
            name='username',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='text_post',
            name='title',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
