# Generated by Django 5.0.6 on 2024-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_text_post_username_alter_text_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_post',
            name='title',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
