# Generated by Django 5.0.6 on 2024-06-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_text_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_post',
            name='rating_dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text_post',
            name='rating_like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text_post',
            name='was_published',
            field=models.BooleanField(default=True),
        ),
    ]
